In [ ]:
#low rank matrix factorization=to factorize the matrix into a product of two matrices with low dimensions.
import numpy

def matrix_factorization(R, P, Q, K, steps=5000, alpha=0.0002, beta=0.02):
    ''' 
    R: rating matrix
    P: |U| * K (User features matrix)
    Q: |D| * K (Item features matrix)
    K: latent features
    steps: iterations
    alpha: learning rate
    beta: regularization parameter'''
    Q = Q.T

    for step in range(steps):
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] > 0:
                    # calculate error
                    eij = R[i][j] - numpy.dot(P[i,:],Q[:,j])

                    for k in range(K):
                        # calculate gradient with a and beta parameter
                        P[i][k] = P[i][k] + alpha * (2 * eij * Q[k][j] - beta * P[i][k])
                        Q[k][j] = Q[k][j] + alpha * (2 * eij * P[i][k] - beta * Q[k][j])

        eR = numpy.dot(P,Q)

        e = 0

        for i in range(len(R)):

            for j in range(len(R[i])):

                if R[i][j] > 0:

                    e = e + pow(R[i][j] - numpy.dot(P[i,:],Q[:,j]), 2) #error square

                    for k in range(K):

                        e = e + (beta/2) * (pow(P[i][k],2) + pow(Q[k][j],2))
        # 0.001: local minimum
        if e < 0.001:

            break

    return P, Q.T

In [ ]:
R = [

     [5,3,0,1],

     [4,0,0,1],

     [1,1,0,5],

     [1,0,0,4],

     [0,1,5,4],
    
     [2,1,3,0],

    ]

R = numpy.array(R)
# N: num of User
N = len(R)
# M: num of Movie
M = len(R[0])
# Num of Features
K = 3


P = numpy.random.rand(N,K)
Q = numpy.random.rand(M,K)

 

nP, nQ = matrix_factorization(R, P, Q, K)

nR = numpy.dot(nP, nQ.T)

In [ ]:
print(nP)
print(nQ)
print(nR)
print(R)

[[-0.27715337  1.06335302  2.1423708 ]
 [-0.15399908  1.23185136  1.43528581]
 [ 1.85575366  0.31403348  0.62191414]
 [ 1.46597035  0.40948127  0.45095105]
 [ 1.19264042  1.37296332  0.87024294]
 [ 0.80737855  0.57035741  0.77672933]]
[[-0.19211354  1.18937812  1.72660605]
 [-0.00397845  0.00478617  1.35057043]
 [ 1.04080891  1.58177368  1.71906226]
 [ 2.41364183  0.48286775  0.53965333]]
[[5.01700412 2.89961469 5.07638891 1.00064745]
 [3.97289551 1.9449631  4.2555721  0.99767944]
 [1.09078987 0.83405884 3.49732396 4.96637933]
 [0.98401012 0.6051687  2.94871463 3.9794099 ]
 [2.90641688 1.17715075 4.90902981 4.01119602]
 [1.86436783 1.04854537 3.0777492  2.64329441]]
[[5 3 0 1]
 [4 0 0 1]
 [1 1 0 5]
 [1 0 0 4]
 [0 1 5 4]
 [2 1 3 0]]


In [ ]:
# python code snippet to conduct the gradient descent algorithm. We set a rating matrix with 4 movies given by 6 users. As you can see, 
# some users didn’t watch some movies before, so the rating is given as 0 in the rating.

In [ ]:
# The predicted matrix is generated below. As you can see, the predicted matrix has similar output with the true values, and the 0 ratings 
# are replaced with the prediction based on the similar users’ preferences on movies.
# In the real-world, the rating matrix is very sparse since every user watches movies at different frequencies. 
# However, the error function RMSE is only calculated with the non-null rating. The missing entries in the rating matrix would be 
# replaced by the dot product of the factor matrices. Therefore, we know what to recommend to the users with the unseen movies based 
# on the prediction.

In [ ]:
# In Conclusion:
# Matrix factorization is a collaborative filtering method to find the relationship between items’ and users’ entities. Latent features, 
# the association between users and movies matrices, are determined to find similarity and make a prediction based on both item and user entities
# The matrix factorization of user and item matrices can be generated when the math cost function RMSE is minimized through matrix factorization. 
# Gradient descent is a method to minimize the cost function.