In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
A=np.array([2,3])
B=np.array([95,30])
result=cosine_similarity(A.reshape(1,-1),B.reshape(1,-1)) #1,-1 for single row and -1,1 for single column(for coverting into 2D array)
print(result)

[[0.77950893]]


In [ ]:
A.reshape(1,-1)

array([[2, 3]])

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
A=np.array([[2,3]])
B=np.array([[500,999]])
result=cosine_similarity(A,B) #1,-1 for single row and -1,1 for single column
print(result)

[[0.99232745]]


In [ ]:
#cosine similarity normalizes the vector and then takes dot product

In [ ]:
from scipy.stats import pearsonr
from numpy.random import randn #rand=numbers from uniform ditstribution betn 0 to 1, randn= normal distribution -infinity to +infinity mean=0 variance=1]

 
# Convert dataframe into series
list1 = 20 * randn(1000) + 100
list2 = 20 * randn(1000) + 50
 
# Apply the pearsonr()
corr, _ = pearsonr(list1, list2)
print('Pearsons correlation: %.3f' % corr)

Pearsons correlation: -0.046


In [ ]:
from numpy.random import rand
rand(10)

array([0.20810031, 0.54908942, 0.88596652, 0.7918049 , 0.85181051,
       0.71466062, 0.25869654, 0.06819684, 0.72845195, 0.13141174])

In [ ]:
randn(10)

array([-1.67261969, -0.47888397,  1.26681059,  1.21895572,  0.58774362,
       -0.99115661, -1.05673297, -1.60771115, -0.17316225, -1.71781743])